apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiRzlpWVd0dmRqcG5hSEJmUjFSRE9WcHFSVGxaU1haMlJXeFRZek00WWpoWk4zYzBaMDVDZWpsSk1qUnlTbUphIgoJCX0KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIgp9
type: kubernetes.io/dockerconfigjson
